image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - build

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .[dev]

lint:
  stage: test
  script:
    - flake8
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

docs:
  stage: build
  script:
    - sphinx-build -b html docs/source docs/build
  artifacts:
    paths:
      - docs/build
    expire_in: 1 week
